import type { SystemSettings } from '@/types'

export const baseSettings: SystemSettings = {
  allowRegistration: true,
  brandText: 'AIChat',
  siteBaseUrl: 'https://chat.example.com',
  chatImageRetentionDays: 30,
  assistantReplyHistoryLimit: 5,
  anonymousRetentionDays: 10,
  anonymousDailyQuota: 5,
  defaultUserDailyQuota: 50,
  battleAllowAnonymous: true,
  battleAllowUsers: true,
  battleAnonymousDailyQuota: 8,
  battleUserDailyQuota: 40,
  battleRetentionDays: 15,
  modelAccessDefaultAnonymous: 'deny',
  modelAccessDefaultUser: 'allow',
  assistantAvatarUrl: null,
  reasoningEnabled: true,
  reasoningDefaultExpand: false,
  reasoningSaveToDb: true,
  reasoningTagsMode: 'default',
  reasoningCustomTags: '',
  streamDeltaChunkSize: 1,
  streamDeltaFlushIntervalMs: 800,
  streamReasoningFlushIntervalMs: 1000,
  streamKeepaliveIntervalMs: 5000,
  openaiReasoningEffort: 'unset',
  reasoningMaxOutputTokensDefault: 32000,
  ollamaThink: false,
  sseHeartbeatIntervalMs: 15000,
  providerMaxIdleMs: 60000,
  providerTimeoutMs: 300000,
  providerInitialGraceMs: 120000,
  providerReasoningIdleMs: 300000,
  reasoningKeepaliveIntervalMs: 0,
  usageEmit: true,
  usageProviderOnly: false,
  webSearchAgentEnable: true,
  webSearchDefaultEngine: 'tavily',
  webSearchResultLimit: 4,
  webSearchDomainFilter: ['example.com'],
  webSearchHasApiKey: true,
  webSearchHasApiKeyTavily: true,
  webSearchHasApiKeyBrave: false,
  webSearchHasApiKeyMetaso: false,
  pythonToolEnable: false,
  pythonToolTimeoutMs: 8000,
  pythonToolMaxOutputChars: 4000,
  pythonToolMaxSourceChars: 4000,
  taskTraceEnabled: true,
  taskTraceDefaultOn: true,
  taskTraceAdminOnly: true,
  taskTraceEnv: 'dev',
  taskTraceRetentionDays: 7,
  taskTraceMaxEvents: 2000,
  taskTraceIdleTimeoutMs: 30000,
}

export const sampleModelList = [
  {
    connectionId: 'openai',
    rawId: 'gpt-4o-mini',
    id: 'gpt-4o-mini',
    name: 'GPT-4o mini',
    provider: 'OpenAI',
    overridden: true,
    capabilitySource: 'manual',
    tags: [{ name: 'vision' }],
    capabilities: {
      vision: true,
      file_upload: false,
      web_search: true,
      image_generation: false,
      code_interpreter: false,
    },
  },
  {
    connectionId: 'local',
    rawId: 'phi-3',
    id: 'phi-3',
    name: 'Phi-3 Turbo',
    provider: 'Azure',
    overridden: false,
    capabilitySource: 'provider',
    tags: [{ name: 'code_interpreter' }],
    capabilities: {
      vision: false,
      file_upload: true,
      web_search: false,
      image_generation: false,
      code_interpreter: true,
    },
  },
] as const

export const adminAuthState = {
  actorState: 'authenticated' as const,
  user: { role: 'ADMIN' },
}

export const userAuthState = {
  actorState: 'authenticated' as const,
  user: { role: 'USER' },
}
